lyceum/about/urls.py
import django.urls

import about.views


app_name = "about"

urlpatterns = [django.urls.path("", about.views.description, name="about")]

lyceum/catalog/urls.py
from django.urls import path, re_path, register_converter

import catalog.converters
import catalog.views

register_converter(catalog.converters.PositiveInt, "positive_int")

app_name = "catalog"

urlpatterns = [
    path("", catalog.views.item_list, name="item_list"),
    path("new/", catalog.views.item_list_new_5, name="item_list_new"),
    path("friday/", catalog.views.item_list_friday, name="item_list_friday"),
    path(
        "unverified/",
        catalog.views.item_list_unverified,
        name="item_list_unverified",
    ),
    path(
        "<int:detail>/",
        catalog.views.item_detail,
        name="item_detail",
    ),
    re_path(
        r"re/(0*[1-9][0-9]*)/",
        catalog.views.echo_num,
        name="item_detail_re",
    ),
    path(
        "converter/<positive_int:num>/",
        catalog.views.echo_num,
        name="item_detail_positive_convert",
    ),
]

lyceum/feedback/urls.py
from django.urls import path

import feedback.views


app_name = "feedback"

urlpatterns = [
    path("", feedback.views.handle_feedback_form, name="feedback"),
]

lyceum/homepage/urls.py
from django.urls import path

import homepage.views


app_name = "homepage"

urlpatterns = [
    path("", homepage.views.home, name="homepage"),
    path("coffee/", homepage.views.teapot, name="coffee"),
    path("echo/", homepage.views.echo_form, name="echo_form"),
    path("echo/submit/", homepage.views.echo_submit, name="echo_submit"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
import django.contrib
import django.urls

import lyceum.settings

urlpatterns = [
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("", django.urls.include("homepage.urls")),
    django.urls.path("catalog/", django.urls.include("catalog.urls")),
    django.urls.path("about/", django.urls.include("about.urls")),
    django.urls.path("download/", django.urls.include("download.urls")),
    django.urls.path("feedback/", django.urls.include("feedback.urls")),
    django.urls.path("tinymce/", django.urls.include("tinymce.urls")),
]

if lyceum.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            "__debug__/",
            django.urls.include("debug_toolbar.urls"),
        ),
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

lyceum/templates/includes/footer.html
{% load static %}

<footer class="container">
  <h6 class="fs-5">Copyright Racoon-Company. <span id="year">{% now "Y" %}</span></h6>
  <script>
    var server_date = Date.parse("{% now 'Y-m-d' %}T{% now 'H:i:s' %}Z");
    var now = Date.now();
    var diff_time_in_sec = Math.abs(server_date - now);
    var diff_days = Math.ceil(diff_time_in_sec / (1000 * 60 * 60 * 24));

    var date = new Date(diff_days < 1 ? now : server_date);
    document.getElementById('year').textContent = date.getFullYear();
  </script>
</footer>

lyceum/templates/includes/form.html
{% for field in form %}
  <div class="mb-3">
    {{ field.errors }}
    {% for error in field.errors %}
      <div id="emailHelp" class="form-text alert alert-danger">{{ error | escape }}</div>
    {% endfor %}
    {{ field.label_tag }}
    {{ field }}
    {% if field.help_text %}
      <p class="help">{{ field.help_text | safe }}</p>
    {% endif %}
  </div>
{% endfor %}

lyceum/templates/includes/header.html
{% load static %}
{% load i18n %}

<div class="container">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="{% url "homepage:homepage"%}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <img src="{% static "img/logo.png" %}" width="40" height="32">
      <span class="fs-4">{% translate "Site_name" %}</span>
    </a>
    {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item"><a href="{% url "homepage:homepage" %}" class="nav-link {% if view_name == "homepage:homepage" %}active{% endif %}">{% translate "Main" %}</a></li>
        <li class="nav-item"><a href="{% url "about:about" %}" class="nav-link {% if view_name == "about:about" %}active{% endif %}">{% translate "About" %}</a></li>
        <li class="nav-item"><a href="{% url "catalog:item_list" %}" class="nav-link {% if view_name == "catalog:item_list" %}active{% endif %}">{% translate "Catalog" %}</a></li>
        <li class="nav-item"><a href="{% url "feedback:feedback" %}" class="nav-link {% if view_name == "feedback:feedback" %}active{% endif %}">{% translate "Feedback" %}</a></li>
        {% if user.is_staff %}
          <li class="nav-item"><a href="/admin/" class="nav-link">{% translate "Admin_panel" %}</a></li>
        {% endif %}
      </ul>
    {% endwith %}
  </header>
</div>

lyceum/templates/includes/item_card.html
{% load static %}

<div class="card" style="width: 18rem;">
    <div class="card-body">
    <h5 class="card-title">{{ item.name }}</h5>
    <p class="card-text">Категория: {{ item.category.name }}</p>
    <p class="card-text">{{ item.text|truncatewords_html:10|safe }}</p>
    <p class="card-text">Теги: {{ item.tags.all|join:", " }}</p>
    <a href="{% url "catalog:item_detail" item.id %}" class="btn btn-primary">Перейти</a>
    </div>
</div>